config/routes.rb
Pawnshop::Application.routes.draw do
  devise_for :users

  root 'pages#index'
  resources :games, only: [:create, :show, :index, :new, :update] do
    resources :pieces, only: [:show, :update]
  end
  resources :dashboard, only: [:show]

end

app/models/game.rb
class Game < ActiveRecord::Base
	after_create :initiate_new_board
	has_many :pieces
	belongs_to :user

  def initiate_new_board
	 	#black pawns
	 	(1..8).each do |n|
	 		Pawn.create(
	 			x_coordinate: n,
	 			y_coordinate: 7,
	 			color: 'black',
	 			game: self)
	 	end

	 	#black pieces
	 	Rook.create(x_coordinate: 1, y_coordinate: 8, color: 'black', game: self)
	 	Knight.create(x_coordinate: 2, y_coordinate: 8, color: 'black', game: self)
	 	Bishop.create(x_coordinate: 3, y_coordinate: 8, color: 'black', game: self)
	 	Queen.create(x_coordinate: 4, y_coordinate: 8, color: 'black', game: self)
	 	King.create(x_coordinate: 5, y_coordinate: 8, color: 'black', game: self)
	 	Bishop.create(x_coordinate: 6, y_coordinate: 8, color: 'black', game: self)
	 	Knight.create(x_coordinate: 7, y_coordinate: 8, color: 'black', game: self)
	 	Rook.create(x_coordinate: 8, y_coordinate: 8, color: 'black', game: self)

	 	#white pawns
	 	(1..8).each do |n|
	 		Pawn.create(
	 			x_coordinate: n,
	 			y_coordinate: 2,
	 			color: 'white',
	 			game: self)
 		end

	 	#white pieces
	 	Rook.create(x_coordinate: 1, y_coordinate: 1, color: 'white', game: self)
	 	Knight.create(x_coordinate: 2, y_coordinate: 1, color: 'white', game: self)
	 	Bishop.create(x_coordinate: 3, y_coordinate: 1, color: 'white', game: self)
	 	Queen.create(x_coordinate: 4, y_coordinate: 1, color: 'white', game: self)
	 	King.create(x_coordinate: 5, y_coordinate: 1, color: 'white', game: self)
	 	Bishop.create(x_coordinate: 6, y_coordinate: 1, color: 'white', game: self)
	 	Knight.create(x_coordinate: 7, y_coordinate: 1, color: 'white', game: self)
	 	Rook.create(x_coordinate: 8, y_coordinate: 1, color: 'white', game: self)
	end

	def stalemate?(color)
		friendly_pieces = pieces_remaining(color)
    available_moves = []
    friendly_pieces.each do |piece|
      1.upto(8) do |x|
        1.upto(8) do |y|
          if piece.valid_move?(x, y) && piece.move_causes_check?(x, y) == false
            available_moves << [x, y]
          end
        end
      end
    end
    return false if available_moves.any?
    true
	end

	def checkmate?(color)
		checked_king = find_king(color)
		return false unless in_check?(color)
		return false if can_block_check?(color)
		return false if can_capture_checking_piece?(color)
		return false if checked_king.can_move_out_of_check?
		true
	end

	def in_check?(color)
		king = pieces.find_by(type: 'King', color: color)
		opponents = opponents_on_board(color)
		opponents.each do |piece|
			if piece.valid_move?(king.x_coordinate, king.y_coordinate)
				@piece_causing_check = piece
				return true
			end
		end
		false
	end

	def can_block_check?(color)
		king = find_king(color)
		friends = pieces.where(color: color).to_a
		enemies = opponents_on_board(color)
		@blockable_coordinates = []

		# horizontal cases
		if king.y_coordinate == @piece_causing_check.y_coordinate
			if king.x_coordinate < @piece_causing_check.x_coordinate
				(king.x_coordinate + 1).upto(@piece_causing_check.x_coordinate - 1).each do |x|
					@blockable_coordinates << [x, king.y_coordinate]
				end
			elsif king.x_coordinate > @piece_causing_check.x_coordinate
				(king.x_coordinate - 1).downto(@piece_causing_check + 1).each do |x|
					@blockable_coordinates << [x, king.y_coordinate]
				end
			end
		end

		# vertical cases
		if king.x_coordinate == @piece_causing_check.x_coordinate
			if king.y_coordinate < @piece_causing_check.y_coordinate
				(king.y_coordinate + 1).upto(@piece_causing_check.y_coordinate - 1).each do |y|
					@blockable_coordinates << [king.x_coordinate, y]
				end
			elsif king.y_coordinate > @piece_causing_check.y_coordinate
				(king.y_coordinate - 1).downto(@piece_causing_check + 1).each do |y|
					@blockable_coordinates << [king.x_coordinate, y]
				end
			end
		end

		#diagonal moves
		if king.x_coordinate < @piece_causing_check.x_coordinate
			if king.y_coordinate < @piece_causing_check.y_coordinate
				(king.x_coordinate + 1).upto(@piece_causing_check.x_coordinate - 1) do |x|
					(king.y_coordinate + 1).upto(@piece_causing_check.x_coordinate - 1) do |y|
						@blockable_coordinates << [x, y]
					end
				end
			elsif king.y_coordinate > @piece_causing_check.y_coordinate
				(king.x_coordinate + 1).upto(@piece_causing_check.x_coordinate - 1) do |x|
					(king.y_coordinate - 1).downto(@piece_causing_check.x_coordinate + 1) do |y|
						@blockable_coordinates << [x, y]
					end
				end
			end
		if king.x_coordinate > @piece_causing_check.x_coordinate
			if king.y_coordinate > @piece_causing_check.y_coordinate
				(king.x_coordinate - 1).downto(@piece_causing_check.x_coordinate + 1) do |x|
					(king.y_coordinate - 1).downto(@piece_causing_check.x_coordinate + 1) do |y|
						@blockable_coordinates << [x, y]
					end
				end
			elsif king.y_coordinate < @piece_causing_check.y_coordinate
				(king.x_coordinate - 1).downto(@piece_causing_check.x_coordinate + 1) do |x|
					(king.y_coordinate + 1).upto(@piece_causing_check.x_coordinate - 1) do |y|
						@blockable_coordinates << [x, y]
					end
				end
			end
		end
	 end
		return false unless @blockable_coordinates.any?
		friends.each do |piece|
			@blockable_coordinates.each do |position|
				return true if piece.valid_move?(position[0], position[1])
			end
		end
		false
	end

	def opponents_on_board(color)
		opposite_color = color == 'black' ? 'white' : 'black'
		pieces.where(x_coordinate: 1..8, y_coordinate: 1..8, color: opposite_color).to_a
	end

	def can_capture_checking_piece?(color)
		friendly_pieces = pieces_remaining(color)

		friendly_pieces.each do |piece|
			if piece.valid_move?(@piece_causing_check.x_coordinate, @piece_causing_check.y_coordinate)
				return true
			end
		end
		false
	end

	def find_king(color)
		pieces.where(type: 'King', color: color).first
	end

	def set_white_player(user)
	 	update_attributes(:white_player_id => user, :turn => user) if white_player_id.nil?
	end

	def set_black_player(user)
		update_attribute(:black_player_id, user) if black_player_id.nil?
	end

	def pieces_remaining(color)
    pieces.where(color: color).to_a
  end

	def check?(color)
		king = find_king(color)
		enemies = opponents_on_board(color)
		@enemies_causing_check = []
	 	enemies.each do |enemy|
			@enemies_causing_check << enemy if enemy.valid_move?(king.x_coordinate, king.y_coordinate)
		end
	 	return true if @enemies_causing_check.any?
	 	false
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		@games = Game.all
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.create(game_params)
		@game.set_white_player(current_user.id)
		redirect_to game_path(@game)
	end

	def show
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		#@game.set_black_player(current_user.id)

		respond_to do | format |
			format.html { redirect_to game_path(current_game) }
			format.js { render 'update.js.erb' }
		end
	end


	private

	helper_method :current_game

	def game_params
		params.require(:game).permit(:name, :white_player_id, :black_player_id)
	end

	def current_game
		@game ||= Game.find(params[:id])
	end


end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/show.html.erb
<DOCTYPE html>
<html>
<head>
</head>

<script>
    $(function() {
        $('.piece').draggable({
            snap: '.square',
            snapMode: 'outer',
            snapTolerance: 40,
            revert: 'invalid',
            opacity: 0.20,
            refreshPositions: true
        });

        $('.square').droppable({
            accept: '.piece',
            drop: function(event, ui) {
                var originalSquare_id = $(ui.draggable).parent().attr('id');
                var capturedPiece = $(this).children().attr('id');
                var piece = $(ui.draggable).attr('id'); 
                var row = $(this).attr('data-row-id');
                var column = $(this).attr('data-column-id');
                var game = <%= current_game.id %>

                console.log("original row and column: " + originalSquare_id );
                console.log("dropped " + piece + " on " + row + "," + column + " for " + game);
                console.log("captured piece id : " + capturedPiece)

                // $.ajax({
                //     type: 'PUT',
                //     url: '/games/'+game+'/pieces/'+piece,
                //     dataType: 'json',
                //     data: {
                //         x: row,
                //         y: column
                //     },
                //     success: function(data) {
                //       $('#'+capturedPiece).fadeOut("slow");
                //       location.reload();
                //     },
                //
                //     error: function(data) {
                //         $('#'+piece).css({'left': 0, 'top': 0});
                //         alert('Invalid Move');
                //         console.log("fail");
                //
                //     }
                // });
            }
        });
    });
</script>

	<body>
		<table>
      <% 8.downto(1) do |column| %>
        <tr class= "column <%= column %>">
          <% 1.upto(8) do |row| %>
            <td class= "square" data-row-id ="<%= row %>" data-column-id = "<%= column %>" id = "<%= row %><%= column %>" >
              <!--check to see if there is a piece-->
              <% if piece = @game.pieces.detect { |piece| piece.x_coordinate == row && piece.y_coordinate == column } %>
                <div class="piece" id="<%= piece.id %>">
                    <%= link_to image_tag("#{piece.color}#{piece.type.downcase}.png"), game_piece_path(@game,piece), remote: true %>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
	</body>
</html>